name: PR Validation

on:
  pull_request:

jobs:
  validate-cli:
    name: Validate CLI on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore CLI only
        run: dotnet restore ./src/CLI/CLI.csproj --framework net9.0

      - name: Build CLI only
        run: dotnet build ./src/CLI/CLI.csproj --framework net9.0 --configuration Release --no-restore

      # - name: Run CLI unit tests
      #   run: dotnet test ./src/CLI.Tests/CLI.Tests.csproj --configuration Release --no-build

      - name: Validate JSON files
        run: |
          for file in $(find ./Services/Resources/Maps -name "*.json"); do
            echo "Validating $file"
            jq empty "$file"
          done

      - name: Check for vulnerable packages
        run: dotnet list package --vulnerable

  validate-maui:
    name: Validate GUI MAUI on macOS
    runs-on: macos-latest
    needs: validate-cli
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install workloads
        run: |
          dotnet workload update
          dotnet workload install maui
          dotnet workload install maui-maccatalyst

      - name: Restore GUI
        run: dotnet restore ./src/GUI/GUI.csproj

      - name: Build GUI
        run: dotnet build ./src/GUI/GUI.csproj --configuration Release --no-restore