name: PR Validation

on:
  pull_request:

jobs:
  build-and-validate:
    name: Build, Test & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Check code formatting
        run: dotnet format --verify-no-changes

      - name: Build with analyzers
        run: dotnet build --configuration Release -warnaserror

      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal

      - name: Validate mapping JSON files
        run: |
            for file in $(find ./Services/Resources/Maps -name "*.json"); do
                echo "Validating $file"
                jq empty "$file"
            done

      - name: Check for vulnerable packages
        run: dotnet list package --vulnerable